Redesign button component #35
iurynogueira/ion-react pull request #37
Opened 2023-02-06 17:48 UTC by Atzac

## Description

Refactoring of the primary button, initially created for testing, and added 3 more variants:

- Secondary
- Ghost
- dashed

2023-02-06 20:11 UTC, iurynogueira requested changes

2023-02-06 20:11 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +  });
Create new tests cases to check styles

2023-02-06 20:11 UTC, iurynogueira commented on src/components/button/button.tsx
> +  type: string;
```suggestion
  type: string;
```

Primary can be default

2023-02-06 20:11 UTC, iurynogueira commented on src/components/button/styles.ts
> +export const StitchesButton = styled('button', {
Change style name

2023-02-06 20:11 UTC, iurynogueira commented on src/components/button/styles.ts
> +      primary: {
danger is missing

2023-02-07 14:37 UTC, Atzac commented on src/components/button/button.test.tsx
> +  });
adjusted

2023-02-07 14:56 UTC, iurynogueira requested changes

2023-02-07 14:56 UTC, iurynogueira commented on package.json
> +    "@testing-library/jest-dom": "^5.16.5"
👍

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +function renderAndGetButton(props: ButtonProps): HTMLElement {
```suggestion
function sut(props: ButtonProps): HTMLElement {
```

https://github.com/Brisanet/typescript/blob/main/docs/Testes%20Unitarios.md#system-under-test-sut

keep this pattern

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +function renderAndGetButton(props: ButtonProps): HTMLElement {
```suggestion
function renderAndGetButton(props: ButtonProps = {...defaultProps}): HTMLElement {
```

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +  render(<Button label={props.label || 'Button'} {...props} />);
```suggestion
  render(<Button {...props} />);
```

You can do this when change above

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +    render(<Button type="primary" label={label} />);
```suggestion
    render(<Button label={label} />);
```

primary is default

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +  test('execute the onClick event', () => {
```suggestion
  test('execute the onClick event', () => {
```

Prefer start spec with `should`

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +  test('execute the onClick event', () => {
```suggestion
  test('should execute event when the button is clicked', () => {
```

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +  test.each(buttonTypes)('should render all types', async (type) => {
```suggestion
  test.each(buttonTypes)('should render button with %s class', async (type) => {
```

2023-02-07 14:56 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +    );
ToHaveClass

2023-02-07 16:33 UTC, Atzac commented on package.json
> +    "@testing-library/jest-dom": "^5.16.5"
@iurynogueira  all ok here?

2023-02-08 11:46 UTC, Deeved commented on src/components/button/button.tsx
> +const Button = ({
```suggestion
const IonButton = ({
```

2023-02-08 11:47 UTC, Deeved commented on src/components/button/button.tsx
>  export default Button;
```suggestion
export default IonButton;
```

2023-02-08 13:02 UTC, Deeved approved these changes

2023-02-08 16:24 UTC, iurynogueira requested changes

2023-02-08 16:24 UTC, iurynogueira commented on src/components/button/button.tsx
> +  label?: string;
```suggestion
  label: string;
```
label is required.

2023-02-08 16:24 UTC, iurynogueira commented on src/components/button/styles.ts
> +            '$neutral5 !important'
check use disabled as a variant

2023-02-08 16:24 UTC, iurynogueira commented on src/components/button/button.tsx
> +  danger,
```suggestion
  disabled = false,
  onClick,
  danger = false,
```

2023-02-08 16:24 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +  disabled: false,
```suggestion
```

2023-02-08 16:24 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +  disabled: false,
```suggestion
```

2023-02-08 16:24 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +  disabled: false,
```suggestion
```

2023-02-08 16:24 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +  disabled: false,
```suggestion
```

2023-02-08 16:24 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +
Create a case with disabled button and other with danger true

2023-02-08 16:58 UTC, Deeved commented on src/components/button/styles.ts
> +}
I think it's a good idea. so we can use it in other components.

2023-02-09 12:17 UTC, iurynogueira requested changes

2023-02-09 12:17 UTC, iurynogueira commented on package.json
> +    "@testing-library/jest-dom": "^5.16.5",
Its a dev dependence

2023-02-10 13:23 UTC, iurynogueira requested changes

2023-02-10 13:23 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +    fireEvent.click(sut({  ...defaultButton }));
```suggestion
    userEvent.click(sut({  ...defaultButton }));
```

change to userEvent, fireEvent not is recommended.

2023-02-10 13:23 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +      expect(className).toContain(`type-${type}`);
very well

2023-02-10 13:23 UTC, iurynogueira commented on src/components/button/button.tsx
> +  onClick,
I believe that we can change to handleClick to not cause confusing with the prop name.

```suggestion
  handleClick,
```

2023-02-10 13:23 UTC, iurynogueira commented on src/components/utils/generateColorStyle.tsx
> +  };
check indent

2023-02-10 13:23 UTC, iurynogueira commented on src/components/utils/generateColorStyle.tsx
> +// Tipo para objeto de estilos  da função geradora de estilos
Keep english

2023-02-10 13:23 UTC, iurynogueira commented on src/components/utils/generateColorStyle.tsx
> +  */
```suggestion
  /* 
    Função que gera cores de Background, Border e cor de
    fonte a fim de reduzir repetições de codigo
  
    Seguir o padrão de parâmetros: 
    1- Cor do background;
    2- Cor da fonte do botão;
    3- (Opicional) Cor da borda;
  */
```

if you are going to comment out a function use the pattern.
https://tsdoc.org/

2023-02-10 13:23 UTC, iurynogueira commented on src/components/utils/generateColorStyle.tsx
> +  }
```suggestion
  }
  
```

missing whiteline

2023-02-10 13:23 UTC, iurynogueira commented on src/components/utils/generateColorStyle.tsx
> +    borderColor && (styles.border = `1px solid ${borderColor}`);
```suggestion
    borderColor && (styles.border = `1px solid ${borderColor}`);
```

Read the styleguide
https://github.com/Brisanet/typescript/blob/main/docs/Style%20Guide.md#control-statements

2023-02-10 13:23 UTC, iurynogueira commented on src/components/utils/generateColorStyle.tsx
> + export function generateColorStyle(
```suggestion
 export function getBgFontBorderColors(
```

I believe that this name make more sense to the return of your function

2023-02-10 13:23 UTC, iurynogueira commented on src/components/button/button.tsx
> +  disabled?: boolean;
```suggestion
  disabled?: boolean = false;
```

implicity this value

2023-02-10 13:23 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +  disabled: false,
```suggestion
  disabled: false,
```
bike shedding

2023-02-10 13:23 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +  disabled: false,
bike shedding

2023-02-10 13:23 UTC, iurynogueira commented on src/stories/button.stories.tsx
> +PrimaryDisabled.args = {
```suggestion
PrimaryDisabledAndDanger.args = {
```

2023-02-10 13:23 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +describe('Button Props', () => {
```suggestion
describe('Button Types', () => {
```

2023-02-10 13:23 UTC, iurynogueira commented on src/components/button/button.test.tsx
> +describe('Button Props', () => {
because you are checking only the types

2023-02-10 16:54 UTC, Deeved commented on src/components/button/button.test.tsx
>      render(<Button label={label} />);
```suggestion
    sut({ label });
```

2023-02-14 11:44 UTC, iurynogueira commented on src/components/utils/getBgFontBorderColors.ts
> + */
👏

2023-02-14 11:44 UTC, iurynogueira commented on src/components/utils/getBgFontBorderColors.ts
> +    [border]: border,
```suggestion
    border: border,
```

2023-02-14 12:03 UTC, iurynogueira approved these changes

2023-02-14 12:04 UTC, merged