feat: create button size variation
iurynogueira/ion-react pull request #72
Opened 2023-02-14 13:38 UTC by Atzac

## Description

 Created Button size variation

2023-02-14 13:47 UTC, wermesonsl approved these changes

2023-02-14 17:19 UTC, Deeved commented on src/components/button/button.tsx
> +type ButtonSizes = SizeType | 'xl';
```suggestion
type ButtonSizes = Exclude<SizeType, 'xs'> | 'xl';
```

2023-02-14 19:05 UTC, Deeved commented
Tem duas coisa para fazer nesse componente que não relacionadas ao tamanho. Como são simples, acredito que dá pra implementar nessa PR.
1 - colocar as stories do botão dentro de navigation 
![image](https://user-images.githubusercontent.com/64809323/218832442-3eb52f7e-77b8-49d1-8ea6-f838f59ca1a5.png)

2 - os estilos secudary e ghost do botão, estão iguais.

2023-02-15 14:09 UTC, iurynogueira requested changes

2023-02-15 14:09 UTC, iurynogueira commented on src/components/utils/getBgFontBorderColors.ts
>   * @returns An Javascript object containing color properties.
```suggestion
 * @returns A Javascript object containing color properties.
```

2023-02-15 14:09 UTC, iurynogueira commented on src/components/utils/getButtonSize.ts
> +) {
Change to object

2023-02-15 14:09 UTC, iurynogueira commented on src/components/utils/getButtonSize.ts
> + * @returns An Javascript object containing size properties.
```suggestion
 * @param fontSize - The size of font
 * @returns A Javascript object containing size properties.
```

2023-02-15 14:09 UTC, iurynogueira commented on src/components/utils/getBgFontBorderColors.test.ts
> +    const expected = { background: 'red', color: 'white', border: '' };
```suggestion
    const expected = { background: 'red', color: 'white' };
```

I believe that did should return this

2023-02-16 18:17 UTC, iurynogueira approved these changes

2023-02-16 18:19 UTC, iurynogueira commented
fix #40

2023-02-16 18:42 UTC, wermesonsl requested changes

2023-02-16 18:42 UTC, wermesonsl commented on src/components/button/styles.ts
>      danger: {
Try use compoundVariants to do this.

2023-02-16 18:47 UTC, wermesonsl approved these changes

2023-02-16 18:50 UTC, merged