feat: body component creation
iurynogueira/ion-react pull request #81
Opened 2023-02-16 20:27 UTC by MarcosOliveir4

## Description
Body Component

- creation:
   - body component
   - stories
   - tests

2023-02-17 17:37 UTC, Atzac approved these changes

2023-02-17 19:02 UTC, iurynogueira requested changes

2023-02-21 13:16 UTC, iurynogueira commented on src/components/typhography/typhography.types.ts
> +}
```suggestion
type IonTyphographySize = 'small' | 'medium' | 'normal';
```

2023-02-21 13:21 UTC, iurynogueira commented on src/components/typhography/typhography.types.ts
> +  size?: keyof MyPick<IonTyphographySize, 'normal' | 'small'>;
```suggestion
  size?: IonBodyTyphographySize;
```

2023-02-21 14:37 UTC, iurynogueira approved these changes

2023-02-21 14:39 UTC, merged