85 create tab component
iurynogueira/ion-react pull request #90
Opened 2023-02-24 19:26 UTC by Atzac

## Description
Tab component with
- size
- direction
- icon
- selected 
- disabled
- badge

2023-02-27 12:12 UTC, jairochaves2 approved these changes

2023-02-27 13:36 UTC, wermesonsl approved these changes

2023-02-27 14:20 UTC, iurynogueira requested changes

2023-02-27 14:20 UTC, iurynogueira commented on src/components/tab/tab.tsx
> +type TabSizes = Exclude<SizeType, 'xs'>;
I believe that is better use Omit.

https://timmousk.com/blog/typescript-omit/#:~:text=As%20you%20can%20see%2C%20omitting,literal%2C%20use%20the%20Exclude%20type.

2023-02-27 14:20 UTC, iurynogueira commented on src/components/tab/tab.tsx
> +  }
check this logic to replace in useState initialize.

2023-03-01 11:48 UTC, iurynogueira approved these changes

2023-03-01 11:48 UTC, merged