91 create badge component
iurynogueira/ion-react pull request #92
Opened 2023-02-28 19:12 UTC by Atzac

## Description

 **Badge component creation**

The Badge component contains two parameters:

- Label: Accepts String or Number, formatting the string also if it contains only numbers
- Type: primary, secondary, neutral or negative

2023-03-01 12:00 UTC, iurynogueira requested changes
Great! :D

2023-03-01 12:00 UTC, iurynogueira commented on src/components/badge/badge.test.tsx
> +    });
```suggestion
    it('should render badge component', async () => {
      sut();
      expect(screen.getByText(defaultBadge.label)).toBeInTheDocument();
    });
```

2023-03-01 12:00 UTC, iurynogueira commented on src/components/badge/badge.test.tsx
> +    it('should render badge component', async () => {
create a new spect to check if primary is default type

2023-03-01 12:00 UTC, iurynogueira commented on src/components/badge/badge.tsx
> +  function formatLabel(badgeLabel: LabelType): LabelType {
arrow function

2023-03-01 18:02 UTC, Atzac commented on src/components/badge/badge.test.tsx
> +
Very nice!

2023-03-01 19:27 UTC, wermesonsl approved these changes

2023-03-06 16:06 UTC, iurynogueira requested changes

2023-03-06 16:46 UTC, iurynogueira approved these changes

2023-03-06 16:46 UTC, merged