feat: implements badge on tab component
iurynogueira/ion-react pull request #96
Opened 2023-03-07 13:41 UTC by Atzac

2023-03-07 18:13 UTC, jairochaves2 commented on src/components/tab/tab.test.tsx
> +};
```suggestion
const getTab = (id='ion-tab') => {
  return screen.getByTestId(id);
};
```

To reuse in lines 125 and 131

2023-03-07 18:32 UTC, jairochaves2 approved these changes

2023-03-07 19:49 UTC, wermesonsl approved these changes

2023-03-08 16:23 UTC, iurynogueira requested changes

2023-03-08 16:23 UTC, iurynogueira commented on src/components/tab/tab.test.tsx
>      it('should render tab without disabled by default', async () => {
```suggestion
    it('should render tab enabled by default', async () => {
```

2023-03-08 16:23 UTC, iurynogueira commented on src/components/tab/tab.test.tsx
> +      expect(screen.queryAllByText('ion-badge')).toHaveLength(0);
screen.queryAllByText('ion-badge') this is correct? I believe that you did should find by badge label or by testid.

2023-03-08 16:23 UTC, iurynogueira commented on src/components/tab/tab.test.tsx
> +      expect(screen.getByTestId('ion-badge').textContent).toBe(label);
```suggestion
      expect(screen.getByTestId('ion-badge').textContent).toBe(label);
```

You can create a function like getTab.

2023-03-09 11:45 UTC, iurynogueira approved these changes

2023-03-09 11:45 UTC, merged